#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=96:00:00
#PBS -l vmem=30gb
#PBS -N cpac

set -x
set -e

echo "getting testing image"
time singularity pull cpac-singularity-image.simg shub://FCP-INDI/C-PAC || singularity pull cpac-singularity-image.simg docker://fcpindi/c-pac:latest

echo "restructuring data"
bl2bids

echo "running cpac"
mkdir -p output tmp

time singularity run -e -B $PWD/tmp:/tmp cpac-singularity-image.simg bids output participant --save_working_dir
