#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=4:00:00
#PBS -l vmem=30gb
#PBS -N cpac

set -x
set -e

echo "getting testing image"
time curl -LOJ https://2630-4733263-gh.circle-artifacts.com/0/cpac-singularity-image.simg

echo "restructuring data"
bl2bids

echo "running cpac"
mkdir -p output tmp

time singularity run -e -B $PWD/tmp:/tmp cpac-singularity-image.simg bids output participant --save_working_dir